# Generated by Django 5.0.6 on 2024-06-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_item_description'),
        ('MainApp', '0002_item_note'),
    ]

    operations = [
    ]
