# Generated by Django 5.0.6 on 2024-06-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_merge_0002_item_description_0002_item_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='note',
        ),
    ]
